[package]
name = "better-spotlight"
version = "0.1.1"
edition = "2024"

[dependencies]
global-hotkey = "0.8"
gpui = "0.2"
image = "0.25"
icns = "0.3"
plist = "1.10"
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["NSApplication", "NSImage", "NSRunningApplication", "NSWorkspace"] }
objc2-foundation = { version = "0.3.2", default-features = false, features = ["NSData", "NSString"] }

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
